'use client';

import { useEffect } from 'react';

declare global {
  interface Window {
    mermaid?: {
      initialize: (config: Record<string, unknown>) => void;
      run: (options: { nodes: NodeListOf<Element> | Element[] }) => Promise<void>;
    };
  }
}

export function MermaidScript() {
  useEffect(() => {
    // 1. Locate all <pre><code class="language-mermaid"> elements generated by marked
    const codeBlocks = document.querySelectorAll('.prose-post pre code.language-mermaid, .prose-post pre code[class*="mermaid"]');
    if (!codeBlocks.length) return;

    // 2. Transform them into <div class="mermaid"> containers with high-contrast styling
    codeBlocks.forEach((codeEl) => {
      const preEl = codeEl.closest('pre');
      if (!preEl || preEl.getAttribute('data-mermaid-processed')) return;

      const codeContent = codeEl.textContent || '';
      const container = document.createElement('div');
      container.className = 'mermaid my-8 p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl overflow-x-auto flex justify-center text-sm';
      container.textContent = codeContent;

      preEl.setAttribute('data-mermaid-processed', 'true');
      preEl.parentNode?.replaceChild(container, preEl);
    });

    // 3. Load Mermaid from CDN dynamically if not loaded
    const initMermaid = () => {
      if (window.mermaid) {
        window.mermaid.initialize({
          startOnLoad: false,
          theme: 'dark',
          themeVariables: {
            primaryColor: '#1e3a8a',
            primaryTextColor: '#ffffff',
            primaryBorderColor: '#60a5fa',
            lineColor: '#38bdf8',
            secondaryColor: '#581c87',
            tertiaryColor: '#064e3b',
            fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
            fontSize: '13px',
          },
          securityLevel: 'loose',
        });

        const mermaidDivs = document.querySelectorAll('.mermaid');
        if (mermaidDivs.length > 0) {
          window.mermaid.run({ nodes: Array.from(mermaidDivs) }).catch((err) => {
            console.error('Mermaid render error:', err);
          });
        }
      }
    };

    if (!window.mermaid) {
      const script = document.createElement('script');
      script.src = 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js';
      script.async = true;
      script.onload = () => initMermaid();
      document.body.appendChild(script);
    } else {
      initMermaid();
    }
  }, []);

  return null;
}
